### ISSUE TITLE
F_AS_T option

### ISSUE THREAD

**Issue by Bodmer** [Bodmer/TFT_ILI9341#1]
Do not comment out the #define F_AS_T line in the User_Setup.h file as the slower SPI access methods currently have a bug.

**Comment by Bodmer** [comment]
Fixed and function memory footprint reduced.

**Comment by fmaimon** [comment]
Why leave this option altogether? Is there an advantage of using the slower option?

**Comment by Bodmer** [comment]
This is a legacy from earlier versions of the library, the aim was to permit the library to be used on SAM or ARM (e.g. DUE or Teensy) which would not work with the F_AS_T option. 

For AVR processors (Atmega328, ATmega2560, ATmega 32u4 etc)  there is no advantage of not using it as th egraphics plotting will be slower.  AS I use the AVR processors I have not got around to fixing an issue when F_AS_T is not use because I have been focusing on other features that I need for my own projects.

**Comment by Bodmer** [comment]
F_AS_T option is still on my list to be fixed!
